// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TV.proto

package org.DS.keithproject.SmartHomeGRPC;

public interface BooleanResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartHomeGRPC.BooleanRes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool msg = 2;</code>
   */
  boolean getMsg();
}
