// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Chromecast.proto

package org.DS.keithproject.SmartHomeGRPC;

public interface ccRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartHomeGRPC.ccResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string dname = 4;</code>
   */
  java.lang.String getDname();
  /**
   * <code>string dname = 4;</code>
   */
  com.google.protobuf.ByteString
      getDnameBytes();

  /**
   * <code>string status = 5;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 5;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>string app = 6;</code>
   */
  java.lang.String getApp();
  /**
   * <code>string app = 6;</code>
   */
  com.google.protobuf.ByteString
      getAppBytes();

  /**
   * <code>int32 volume = 7;</code>
   */
  int getVolume();
}
