// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Chromecast.proto

package org.DS.keithproject.SmartHomeGRPC;

public final class ChromecastServiceImpl {
  private ChromecastServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartHomeGRPC_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartHomeGRPC_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartHomeGRPC_StringRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartHomeGRPC_StringRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartHomeGRPC_StringResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartHomeGRPC_StringResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartHomeGRPC_BooleanReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartHomeGRPC_BooleanReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartHomeGRPC_BooleanRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartHomeGRPC_BooleanRes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartHomeGRPC_valRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartHomeGRPC_valRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartHomeGRPC_valResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartHomeGRPC_valResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartHomeGRPC_ccResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartHomeGRPC_ccResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020Chromecast.proto\022\rSmartHomeGRPC\"\007\n\005Emp" +
      "ty\"\035\n\rStringRequest\022\014\n\004text\030\001 \001(\t\"\036\n\016Str" +
      "ingResponse\022\014\n\004text\030\001 \001(\t\"\031\n\nBooleanReq\022" +
      "\013\n\003msg\030\002 \001(\010\"\031\n\nBooleanRes\022\013\n\003msg\030\002 \001(\010\"" +
      "\034\n\nvalRequest\022\016\n\006length\030\003 \001(\005\"\035\n\013valResp" +
      "onse\022\016\n\006length\030\003 \001(\005\"D\n\006ccResp\022\r\n\005dname\030" +
      "\004 \001(\t\022\016\n\006status\030\005 \001(\t\022\013\n\003app\030\006 \001(\t\022\016\n\006vo" +
      "lume\030\007 \001(\0052\206\003\n\021ChromecastService\022>\n\rinit" +
      "ialDevice\022\024.SmartHomeGRPC.Empty\032\025.SmartH" +
      "omeGRPC.ccResp\"\000\022R\n\021changeApplication\022\034." +
      "SmartHomeGRPC.StringRequest\032\035.SmartHomeG" +
      "RPC.StringResponse\"\000\022I\n\014changeVolume\022\031.S" +
      "martHomeGRPC.valRequest\032\032.SmartHomeGRPC." +
      "valResponse\"\0000\001\022?\n\005onOff\022\031.SmartHomeGRPC" +
      ".BooleanReq\032\031.SmartHomeGRPC.BooleanRes\"\000" +
      "\022Q\n\020changeDeviceName\022\034.SmartHomeGRPC.Str" +
      "ingRequest\032\035.SmartHomeGRPC.StringRespons" +
      "e\"\000B<\n!org.DS.keithproject.SmartHomeGRPC" +
      "B\025ChromecastServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SmartHomeGRPC_Empty_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SmartHomeGRPC_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartHomeGRPC_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_SmartHomeGRPC_StringRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SmartHomeGRPC_StringRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartHomeGRPC_StringRequest_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_SmartHomeGRPC_StringResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_SmartHomeGRPC_StringResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartHomeGRPC_StringResponse_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_SmartHomeGRPC_BooleanReq_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_SmartHomeGRPC_BooleanReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartHomeGRPC_BooleanReq_descriptor,
        new java.lang.String[] { "Msg", });
    internal_static_SmartHomeGRPC_BooleanRes_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_SmartHomeGRPC_BooleanRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartHomeGRPC_BooleanRes_descriptor,
        new java.lang.String[] { "Msg", });
    internal_static_SmartHomeGRPC_valRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_SmartHomeGRPC_valRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartHomeGRPC_valRequest_descriptor,
        new java.lang.String[] { "Length", });
    internal_static_SmartHomeGRPC_valResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_SmartHomeGRPC_valResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartHomeGRPC_valResponse_descriptor,
        new java.lang.String[] { "Length", });
    internal_static_SmartHomeGRPC_ccResp_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_SmartHomeGRPC_ccResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartHomeGRPC_ccResp_descriptor,
        new java.lang.String[] { "Dname", "Status", "App", "Volume", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
