// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Speaker.proto

package org.DS.keithproject.SmartHomeGRPC;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartHomeGRPC.Empty)
    com.google.protobuf.MessageOrBuilder {
}
