// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TV.proto

package org.DS.keithproject.SmartHomeGRPC;

public final class TVServiceImpl {
  private TVServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartHomeGRPC_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartHomeGRPC_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartHomeGRPC_StringRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartHomeGRPC_StringRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartHomeGRPC_StringResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartHomeGRPC_StringResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartHomeGRPC_BooleanReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartHomeGRPC_BooleanReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartHomeGRPC_BooleanRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartHomeGRPC_BooleanRes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartHomeGRPC_valRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartHomeGRPC_valRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartHomeGRPC_valResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartHomeGRPC_valResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartHomeGRPC_tvResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartHomeGRPC_tvResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\010TV.proto\022\rSmartHomeGRPC\"\007\n\005Empty\"\035\n\rSt" +
      "ringRequest\022\014\n\004text\030\001 \001(\t\"\036\n\016StringRespo" +
      "nse\022\014\n\004text\030\001 \001(\t\"\031\n\nBooleanReq\022\013\n\003msg\030\002" +
      " \001(\010\"\031\n\nBooleanRes\022\013\n\003msg\030\002 \001(\010\"\034\n\nvalRe" +
      "quest\022\016\n\006length\030\003 \001(\005\"\035\n\013valResponse\022\016\n\006" +
      "length\030\003 \001(\005\"H\n\006tvResp\022\r\n\005dname\030\004 \001(\t\022\016\n" +
      "\006status\030\005 \001(\t\022\016\n\006volume\030\006 \001(\005\022\017\n\007channel" +
      "\030\007 \001(\0052\222\004\n\tTvService\022>\n\rinitialDevice\022\024." +
      "SmartHomeGRPC.Empty\032\025.SmartHomeGRPC.tvRe" +
      "sp\"\000\022I\n\014changeVolume\022\031.SmartHomeGRPC.val" +
      "Request\032\032.SmartHomeGRPC.valResponse\"\0000\001\022" +
      "?\n\004mute\022\031.SmartHomeGRPC.BooleanReq\032\032.Sma" +
      "rtHomeGRPC.valResponse\"\000\022?\n\005onOff\022\031.Smar" +
      "tHomeGRPC.BooleanReq\032\031.SmartHomeGRPC.Boo" +
      "leanRes\"\000\022Q\n\020changeDeviceName\022\034.SmartHom" +
      "eGRPC.StringRequest\032\035.SmartHomeGRPC.Stri" +
      "ngResponse\"\000\022[\n\026changeDeviceNameStream\022\034" +
      ".SmartHomeGRPC.StringRequest\032\035.SmartHome" +
      "GRPC.StringResponse\"\000(\0010\001\022H\n\rchangeChann" +
      "el\022\031.SmartHomeGRPC.valRequest\032\032.SmartHom" +
      "eGRPC.valResponse\"\000B4\n!org.DS.keithproje" +
      "ct.SmartHomeGRPCB\rTVServiceImplP\001b\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SmartHomeGRPC_Empty_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SmartHomeGRPC_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartHomeGRPC_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_SmartHomeGRPC_StringRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SmartHomeGRPC_StringRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartHomeGRPC_StringRequest_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_SmartHomeGRPC_StringResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_SmartHomeGRPC_StringResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartHomeGRPC_StringResponse_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_SmartHomeGRPC_BooleanReq_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_SmartHomeGRPC_BooleanReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartHomeGRPC_BooleanReq_descriptor,
        new java.lang.String[] { "Msg", });
    internal_static_SmartHomeGRPC_BooleanRes_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_SmartHomeGRPC_BooleanRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartHomeGRPC_BooleanRes_descriptor,
        new java.lang.String[] { "Msg", });
    internal_static_SmartHomeGRPC_valRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_SmartHomeGRPC_valRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartHomeGRPC_valRequest_descriptor,
        new java.lang.String[] { "Length", });
    internal_static_SmartHomeGRPC_valResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_SmartHomeGRPC_valResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartHomeGRPC_valResponse_descriptor,
        new java.lang.String[] { "Length", });
    internal_static_SmartHomeGRPC_tvResp_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_SmartHomeGRPC_tvResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartHomeGRPC_tvResp_descriptor,
        new java.lang.String[] { "Dname", "Status", "Volume", "Channel", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
