// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TV.proto

package org.DS.keithproject.SmartHomeGRPC;

public interface valRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartHomeGRPC.valRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 length = 3;</code>
   */
  int getLength();
}
